### ISSUE TITLE
Upgrade to 0.37

### ISSUE THREAD

**Issue by override80** [pmint93/helm-charts#4]
Hi, thanks for hosting the chart. Did you ever try to upgrade an existing 0.36.X metabase helm chart installation to 0.37? Do you think it could be just a metter of bumping the image version in the templates or could it involve something else?

**Comment by pmint93** [comment]
Hi @override80 ,
It's depends on metabase changes since 0.36.X, so you can look at the change log in [metabase releases](https://github.com/metabase/metabase/releases) to see if there is anything we should consider.

If metabase follow [semver](https://semver.org/) correctly, bumping version from 0.36 to 0.37 meaning that there is no breaking changes and you can just bump the image version and you'll be fine

**Comment by override80** [comment]
Hi! I'll try the update in these days and let you know if issues arise! Thankyou!
